# Generated by Django 5.2.6 on 2025-11-19 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtorDublador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nacionalidade', models.CharField(max_length=50)),
                ('data_nascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('anime', 'ANIME'), ('filme', 'FILME'), ('serie', 'SERIE'), ('livro', 'LIVRO')], max_length=10)),
                ('ano_lancamento', models.DateField(blank=True, null=True)),
                ('estudio_produtora', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.PositiveIntegerField()),
                ('genero', models.CharField(choices=[('M', 'Mulher'), ('H', 'Homem'), ('O', 'Outro')], max_length=1)),
                ('especie', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('ator_dublador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_personagens.atordublador')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_personagens.obra')),
            ],
        ),
    ]
