# Generated by Django 5.2.6 on 2025-11-19 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_personagens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='atordublador',
            old_name='nacionalidade',
            new_name='nacionaliadde',
        ),
        migrations.AlterField(
            model_name='obra',
            name='tipo',
            field=models.CharField(choices=[('Anime', 'ANIME'), ('Filme', 'FILME'), ('Série', 'SERIE'), ('Livro', 'LIVRO')], max_length=5),
        ),
        migrations.AlterField(
            model_name='obra',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='ator_dublador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_personagens.atordublador'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='especie',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='genero',
            field=models.CharField(choices=[('M', 'Mulher'), ('H', 'Homi'), ('o', 'Outro')], max_length=1),
        ),
        migrations.CreateModel(
            name='personagemHabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_personagens.habilidade')),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_personagens.personagem')),
            ],
        ),
        migrations.CreateModel(
            name='relacionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relacionamento', models.CharField(choices=[('A', 'Amigo'), ('I', 'Inimigo'), ('D', 'Desconhecido'), ('N', 'Namorado')], max_length=13)),
                ('personagem_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personagem_destino', to='api_personagens.personagem')),
                ('personagem_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personagem_origem', to='api_personagens.personagem')),
            ],
        ),
    ]
