# Generated by Django 5.2.6 on 2025-11-19 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_personagens', '0002_habilidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atordublador',
            name='nacionaliadde',
        ),
        migrations.RemoveField(
            model_name='relacionamento',
            name='relacionamento',
        ),
        migrations.AddField(
            model_name='atordublador',
            name='nacionalidade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='relacionamento',
            name='tipo_relacionamento',
            field=models.CharField(choices=[('amigo', 'Amigo'), ('Aliado', 'Aliado'), ('inimigo', 'Inimigo'), ('parente', 'Parente')], default='amigo', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='obra',
            name='tipo',
            field=models.CharField(choices=[('Anime', 'ANIME'), ('Filme', 'FILME'), ('Serie', 'SERIE'), ('Livro', 'LIVRO')], max_length=5),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='ator_dublador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_personagens.atordublador'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='especie',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='genero',
            field=models.CharField(choices=[('M', 'Mulher'), ('H', 'HOMEM'), ('O', 'Outro')], max_length=5),
        ),
        migrations.AlterField(
            model_name='personagemhabilidade',
            name='habilidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidade', to='api_personagens.habilidade'),
        ),
        migrations.AlterField(
            model_name='personagemhabilidade',
            name='personagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personagem', to='api_personagens.personagem'),
        ),
        migrations.AlterField(
            model_name='relacionamento',
            name='personagem_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacionamentos_de_destino', to='api_personagens.personagem'),
        ),
        migrations.AlterField(
            model_name='relacionamento',
            name='personagem_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacionamentos_de_origem', to='api_personagens.personagem'),
        ),
    ]
